apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry-operator
---  
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-opentelemetry-operator-
  namespace: openshift-opentelemetry-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/opentelemetry-product.openshift-opentelemetry-operator: ''
  name: opentelemetry-product
  namespace: openshift-opentelemetry-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# startingCSV: opentelemetry-operator.v0.107.0-5